### ISSUE TITLE
Unable to register multiple monitors for the same object

### ISSUE THREAD

**Issue by tobespc** [RuntimeTools/SwiftMetrics#10]
If I run this code
#####
import SwiftMetricsDash
import SwiftMetrics

let sm = try SwiftMetrics()
let monitoring = sm.monitor()

func processCPU(cpu: CPUData) {
   print("\nThis is a custom CPU event response.\n cpu.timeOfSample = \(cpu.timeOfSample),\n cpu.percentUsedByApplication = \(cpu.percentUsedByApplication),\n cpu.percentUsedBySystem = \(cpu.percentUsedBySystem).\n")
}
func processCPU2(cpu: CPUData) {
   print("\nThis is a custom CPU22222222222222 event response.\n cpu.timeOfSample = \(cpu.timeOfSample),\n cpu.percentUsedByApplication = \(cpu.percentUsedByApplication),\n cpu.percentUsedBySystem = \(cpu.percentUsedBySystem).\n")
}

monitoring.on(processCPU)
monitoring.on(processCPU2)

print("press a key")

let response = readLine(strippingNewline: true)  
######

only the first monitor gets called

**Comment by mattcolegate** [comment]
This has exposed 2 bugs:
1.) In SwiftMonitor.on(), when it calls EventEmitter.subscribe() the passed-through callback is still of type <T: SMData>(T) -> (), despite the logging reporting type(of: callback) as the correct type! All callbacks were therefore being stored in customObservers rather than their type-specific observer array. Well, they would have been, if not for
2.) In SwiftMonitor.EventEmitter.subscribe<T: SMData>() appending the new callback to the observer variable just updated the observer variable - it didn't update the contents of customObservers[index]. This meant that only the first function of a given callback type would be stored for execution later, hence the processCPU2 function above being 'ignored'

Bug 1.) can be fixed by overloading SwiftMonitor.on() with the callback types we know so that the pass-through type is preserved. Bug 2.) can be fixed by making sure we update customObservers[index].

**Comment by mattcolegate** [comment]
Note this will require an update to https://github.com/RuntimeTools/SwiftMetrics-kitura to extend SwiftMonitor.on() with the HTTPData type.

**Comment by mattcolegate** [comment]
Also have to overload SwiftMonitor.raiseEvent() for the same reasons as bug 1.)

**Comment by tobespc** [comment]
closing as now fixed
