### ISSUE TITLE
HTTP Incoming Request Chart does not always correctly display response times

### ISSUE THREAD

**Issue by vincent-coetzee** [RuntimeTools/SwiftMetrics#100]
When running a server that has a significant number of incoming HTTP requests, the HTTP Incoming Requests chart does not correctly display. It almost seems as if some of the times for the incoming requests move backward ( it seems to occur when the time taken to handle the request is large i.e. above 1000ms ). I'm not sure how else to describe what happens, I attach a picture of the chart which should make the error clear. This happens when the server is run under Ubuntu Linux 14.04.

![untitled](https://cloud.githubusercontent.com/assets/12059694/25063278/4d93555c-21e0-11e7-895d-4f925e797e16.jpeg)

**Comment by sjanuary** [comment]
I think the chart is using the response start time for the x-axis, but if a response takes a very long time then the data point is received and plotted after supsequent responses which completed more quickly. I think the points are right, it just looks strange because the line goes backwards.  We could possibly sort the data before drawing the line.

**Comment by stalleyj** [comment]
This is happening when an http request completes after one that started later, ie request1 starts, request2 starts, request2 ends, request1 ends. The data is displayed in the order that is received rather than in the order the request started. We will work on fixing this problem. If you have a testcase that displays this problem, that would be really helpful.

**Comment by vincent-coetzee** [comment]
Hi there

Unfortunately without giving you access to our entire Kitura server and our suite of tests, I can’t give you some code that reproduces the error. I can however reliably reproduce the problem by creating the following scenario :-

1. Start a long running process ( call this process A) that continues to make calls to the Kitura server as long as it runs
2. Create another process ( call this process B ), that makes some calls to the Kitura server that take several seconds to execute. 
3. Leave process A running, and then run process B.
4. Every time process B completes executing the chart will jumps backwards as shown in the image I uploaded. 

Hope this clarifies the matter.

Many thanks

Vincent Coetzee
