### ISSUE TITLE
Failed to push the Bluemix application - The dependency graph could not be satisfied.

### ISSUE THREAD

**Issue by qiyaod** [RuntimeTools/SwiftMetrics#53]
My application can be pushed successfully yesterday. But when I push it today got the following error for both stage1 and production env:

STG/0 Cloning https://github.com/IBM-Swift/CloudConfiguration.git  Mar 1, 2017 12:56:29 PM
STG/0 HEAD is now at ccaedb3 Merge pull request #13 from IBM-Swift/scaling Mar 1, 2017 12:56:30 PM
STG/0 Resolved version: 1.1.2 Mar 1, 2017 12:56:30 PM
STG/0 swift-package: error: The dependency graph could not be satisfied (https://github.com/IBM-Swift/Swift-cfenv.git) Mar 1, 2017 12:56:31 PM
STG/0 Failed to compile droplet Mar 1, 2017 12:56:31 PM
STG/0 Exit status 223 Mar 1, 2017 12:56:31 PM
STG/0 Staging failed: Exited with status 223 Mar 1, 2017 12:56:31 PM
STG/0 Destroying container Mar 1, 2017 12:56:31 PM
API/0 Failed to stage application: staging failed Mar 1, 2017 12:56:31 PM
STG/0 Successfully destroyed container

Created a complete new Swift app, download the app and add the following to the Package.swift

.Package(url: "https://github.com/RuntimeTools/SwiftMetrics.git", majorVersion: 0)

Have the following same error when build locally: swift build -Xlinker -lc++

QideMacBook-Pro:SwiftTest qiyaod$ swift build -Xlinker -lc++
Cloning https://github.com/RuntimeTools/SwiftMetrics.git
HEAD is now at f4d68a0 only check agent config
Resolved version: 0.0.13
Cloning https://github.com/RuntimeTools/omr-agentcore.git
HEAD is now at c35de73 Correct CPU timestamp on Mac to msSinceEpoch
Resolved version: 3.1.1
Cloning https://github.com/IBM-Swift/Kitura-Request.git
HEAD is now at 2634d14 Updated dependencies
Resolved version: 0.7.0
Cloning https://github.com/IBM-Swift/CloudConfiguration.git
HEAD is now at ccaedb3 Merge pull request #13 from IBM-Swift/scaling
Resolved version: 1.1.2
error: The dependency graph could not be satisfied (https://github.com/IBM-Swift/Swift-cfenv.git)

**Comment by qiyaod** [comment]
Checked package for https://github.com/IBM-Swift/CloudConfiguration

let package = Package(
    name: "CloudConfiguration",
    dependencies: [
        .Package(url: "https://github.com/IBM-Swift/Swift-cfenv.git", majorVersion: 3)
    ]
)

But for https://github.com/IBM-Swift/Swift-cfenv/releases, there is only v2.0.2, not sure if this is the root cause of the problem.

**Comment by qiyaod** [comment]
Also there is the following for https://github.com/IBM-Swift/Swift-cfenv/releases

4 days ago 
3.0.0  …
Updated visibility modifiers for certain properties.
 dff3a5d   zip   tar.gz

**Comment by tobespc** [comment]
we have a travis integration build that runs for swiftmetrics and in this case it has not run (investigating why).  I have it failing on mac os but not on linux

**Comment by tobespc** [comment]
can you make sure all your packages are deleted before building please.  We no longer use swift-cfenv but it seems without a clean build, this error occurs.

**Comment by qiyaod** [comment]
I cleaned everything and build again, still the same problem. I noticed that during the build it always clone the version 2.0.3
Cloning https://github.com/IBM-Swift/Swift-cfenv.git
HEAD is now at 28c8d04 Merge pull request #48 from IBM-Swift/issue.versioning
Resolved version: 2.0.3

But the https://github.com/IBM-Swift/CloudConfiguration.git package depends on .Package(url: "https://github.com/IBM-Swift/Swift-cfenv.git", majorVersion: 3)

Cloning https://github.com/IBM-Swift/CloudConfiguration.git
HEAD is now at ccaedb3 Merge pull request #13 from IBM-Swift/scaling
Resolved version: 1.1.2

**Comment by tobespc** [comment]
The problem is with the cf-deployment-tracker dependancy.  This has not been updated yet correctly.  A simple kitura app you can use is this one to test with

#######
import SwiftMetricsDash
import SwiftMetrics
import Kitura

let sm = try SwiftMetrics()
let smd = try SwiftMetricsDash(swiftMetricsInstance: sm)

let router = Router()
router.get("/") {
    request, response, next in
    response.status(.OK).send("Hello, world!")
    try response.end()
}
Kitura.addHTTPServer(onPort: 8090, with: router)
Kitura.run()   
########

with the Package.swift just requiring a single dependancy

.Package(url: "https://github.com/RuntimeTools/SwiftMetrics/SwiftMetrics.git",  majorVersion: 0)

**Comment by mattcolegate** [comment]
There is a problem with https://github.com/IBM-Bluemix/cf-deployment-tracker-client-swift - in their latest tag (2.0.0) their Package.swift contains
`.Package(url: "https://github.com/IBM-Swift/CloudConfiguration", majorVersion: 1),`
This should contain "https://github.com/IBM-Swift/CloudConfiguration.git" otherwise Swift Package Manager thinks it is a different package to the one specified in SwiftMetrics' Package.swift and tries to download them both, causing an error. I have commented on the relevant pull request (https://github.com/IBM-Bluemix/cf-deployment-tracker-client-swift/pull/40) and notified @rolivieri on Slack.
