### ISSUE TITLE
Use "Auto-Scaling" as prefix to identify Auto-Scaling service.

### ISSUE THREAD

**Issue by qibobo** [RuntimeTools/SwiftMetrics#54]
The service label could be Auto-Scaling,Auto-Scaling-Dedicated,Auto-Scaling-Local, Auto-Scaling-Private-Qiyang or some thing like Auto-Scaling****.

**Comment by qibobo** [comment]
We have this issue for several times.

**Comment by mattcolegate** [comment]
@rolivieri, this is the main problem we have in using getServices(type:). To prevent this cycle recurring. I would like to use this issue to thrash out between you, me and @qibobo exactly how to solve this. I see two options:

1. The Auto-scaling service label should only ever be Auto-Scaling. @qibono, can you detail how you create your auto-scaling service with the differing labels for us please?
2. The Auto-scaling label can be anything conforms to the pattern Auto-Scaling[.*]. @rolivieri, can ConfiguarationManager.getServices(type:) be altered so that the match check for type becomes a prefix match-check? Would this cause problems?

Let's get this problem sorted once and for all gentlemen.

**Comment by rolivieri** [comment]
@mattcolegate - Last time we discussed the name could be anything the developer wants but the label should always be Auto-Scaling. I don't think developers that use Bluemix can change the label for the auto-scaling service. Now, what I am guessing is happening here is that @qibobo is part of the auto-scaling team and because of that, they have rights to label their service in any way they want. And, hence, the issue you guys are seeing. What I think we should do is something along point 2 you described above (Auto-Scaling[.*].) I will change Swift-cfenv to address this and let you guys once it is done. Thanks for providing the additional info.

**Comment by rolivieri** [comment]
@mattcolegate @qibobo New version of Swift-cfenv is now available: 3.0.1. No changes are required to SwiftMetrics. @qibobo Make sure you clean up your Packages folder to force SwiftPM download Swift-cfenv 3.0.1.

**Comment by qibobo** [comment]
@mattcolegate @rolivieri  The label of Auto-Scaling service will be different in some Bluemix envs. When in YP it is "Auto-Scaling", and when in Bluemix local or dedicated envs or our test envs it may be "Auto-Scaling***". So we should use "Auto-Scaling" as the prefix the get the service.

**Comment by rolivieri** [comment]
@qibobo Got it, thx for the additional info. I had initially wrongly thought that the label was always the same in all environments. After the changes we made yesterday to the config library, you should be good now. Let us know if you run into another problem regarding the label.

**Comment by mattcolegate** [comment]
Closing this work item as it appears to be fixed in Swift-cfenv.
